services:
  db:
    image: mysql:8.0
    container_name: name-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: names
      MYSQL_USER: names
      MYSQL_PASSWORD: "k/CG@c[@*JqNkICm"
      MYSQL_ROOT_PASSWORD: "root"
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:5
    container_name: name-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"

volumes:
  db_data:
